config/routes.rb
Rails.application.routes.draw do
  get 'available_skills_debug/index'
  resources :character_contacts
  resources :contacts
  get 'debug_homepage/index'
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/chummer_download", to:'chummer_download#index'
  post "/chummer_download/download", to: 'chummer_download#download'
  resources :characters
  get "/character/upload", to:"characters#upload_user_side"
  post "/character/upload", to:"characters#upload"
  get '/listings/skills', to:'listing_debug#skills'
  get '/listings/qualities', to:'listing_debug#qualities'
  get '/listings/items', to:'listing_debug#items'
  root to: 'debug_homepage#index'
end

app/models/character_contact.rb
class CharacterContact < ApplicationRecord
  belongs_to :contact
  belongs_to :character
  around_destroy :destroy_character_only_contacts
  def to_chum5_nokogiri()
    contact_nokogiri=contact.to_chum5_nokogiri()
    # Overwriting the placeholder values with the ones for our content
    contact_nokogiri.xpath('.//loyalty').first.content=loyalty
    contact_nokogiri.xpath('.//blackmail').first.content=blackmail
    contact_nokogiri.xpath('.//family').first.content=family
    contact_nokogiri
  end
  def to_chum5_xml()
    to_chum5_nokogiri().to_xml
  end
  class<<self
    def CharacterContacts_from_chum5_xml(character, nokogiri_document)
      # Alot like the one from the contact model ... just itterate over 
      # every contact in the document
      nokogiri_document.xpath('.//contacts/contact').each do |contact|
        CharacterContact_from_chum5_xml(character,contact)
      end
    end
    def CharacterContact_from_chum5_xml(character, nokogiri_node)
      # Ok, let's go ahead and grab a new CharacterContact
      character_contact=CharacterContact.new()
      # Next, let's go ahead Create the character we are going to need
      character_contact.contact=Contact.contact_from_chum5_xml(nokogiri_node)
      # Sweet, let's go ahead and set our character
      character_contact.character=character
      # And we should grab the loyalty for that contact
      character_contact.loyalty=nokogiri_node.xpath('.//loyalty/text()').to_s.to_i
      character_contact.blackmail=nokogiri_node.xpath('.//blackmail/text()').to_s.downcase[0]=='t'
      character_contact.family=nokogiri_node.xpath('.//family/text()').to_s.downcase[0]=='t'
      # Last, but not least let's save this thing!
      character_contact.save!
    end
  end
  private
  def destroy_character_only_contacts()
    c2=contact # Temporarly storing the contact
    yield      # Yielding for Around
    if(c2.player_custom && c2.character_contact.length==0)
      c2.destroy
    end
  end
end

app/controllers/character_contacts_controller.rb
class CharacterContactsController < ApplicationController
  before_action :set_character_contact, only: [:show, :edit, :update, :destroy]

  # GET /character_contacts
  # GET /character_contacts.json
  def index
    @character_contacts = CharacterContact.all
  end

  # GET /character_contacts/1
  # GET /character_contacts/1.json
  def show
  end

  # GET /character_contacts/new
  def new
    @character_contact = CharacterContact.new
  end

  # GET /character_contacts/1/edit
  def edit
  end

  # POST /character_contacts
  # POST /character_contacts.json
  def create
    @character_contact = CharacterContact.new(character_contact_params)

    respond_to do |format|
      if @character_contact.save
        format.html { redirect_to @character_contact, notice: 'Character contact was successfully created.' }
        format.json { render :show, status: :created, location: @character_contact }
      else
        format.html { render :new }
        format.json { render json: @character_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /character_contacts/1
  # PATCH/PUT /character_contacts/1.json
  def update
    respond_to do |format|
      if @character_contact.update(character_contact_params)
        format.html { redirect_to @character_contact, notice: 'Character contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @character_contact }
      else
        format.html { render :edit }
        format.json { render json: @character_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /character_contacts/1
  # DELETE /character_contacts/1.json
  def destroy
    @character_contact.destroy
    respond_to do |format|
      format.html { redirect_to character_contacts_url, notice: 'Character contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character_contact
      @character_contact = CharacterContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_contact_params
      params.require(:character_contact).permit(:contact_id, :character_id, :loyalty)
    end
end

app/helpers/character_contacts_helper.rb
module CharacterContactsHelper
end

app/views/character_contacts/_form.html.erb
<%= form_with(model: character_contact, local: true) do |form| %>
  <% if character_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character_contact.errors.count, "error") %> prohibited this character_contact from being saved:</h2>

      <ul>
      <% character_contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%#Need a more elegant way of doing this unfortunatly ...%>
  <div class="field">
    <%= form.label :contact_id %>
    <%= form.text_field :contact_id %>
  </div>

  <div class="field">
    <%= form.label :character_id %>
    <%= form.text_field :character_id %>
  </div>

  <div class="field">
    <%= form.label :loyalty %>
    <%= form.number_field :loyalty %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/character_contacts/edit.html.erb
<h1>Editing Character Contact</h1>

<%= render 'form', character_contact: @character_contact %>

<%= link_to 'Show', @character_contact %> |
<%= link_to 'Back', character_contacts_path %>

app/views/character_contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Character Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Contact Name</th>
      <th>Character Alias</th>
      <th>Loyalty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @character_contacts.each do |character_contact| %>
      <tr>
        <td><%= character_contact.contact.name %></td>
        <td><%= character_contact.character.alias %></td>
        <td><%= character_contact.loyalty %></td>
        <td><%= link_to 'Show', character_contact %></td>
        <td><%= link_to 'Edit', edit_character_contact_path(character_contact) %></td>
        <td><%= link_to 'Destroy', character_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character Contact', new_character_contact_path %>

app/views/character_contacts/new.html.erb
<h1>New Character Contact</h1>

<%= render 'form', character_contact: @character_contact %>

<%= link_to 'Back', character_contacts_path %>

app/views/character_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contact:</strong>
  <%= @character_contact.contact %>
</p>

<p>
  <strong>Character:</strong>
  <%= @character_contact.character %>
</p>

<p>
  <strong>Loyalty:</strong>
  <%= @character_contact.loyalty %>
</p>

<%= link_to 'Edit', edit_character_contact_path(@character_contact) %> |
<%= link_to 'Back', character_contacts_path %>