config/routes.rb
Rails.application.routes.draw do
  get 'available_skills_debug/index'
  resources :character_contacts
  resources :contacts
  get 'debug_homepage/index'
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/chummer_download", to:'chummer_download#index'
  post "/chummer_download/download", to: 'chummer_download#download'
  resources :characters
  get "/character/upload", to:"characters#upload_user_side"
  post "/character/upload", to:"characters#upload"
  get '/listings/skills', to:'listing_debug#skills'
  get '/listings/qualities', to:'listing_debug#qualities'
  get '/listings/items', to:'listing_debug#items'
  root to: 'debug_homepage#index'
end

app/controllers/debug_homepage_controller.rb
class DebugHomepageController < ApplicationController
  def index
  end
end

app/helpers/debug_homepage_helper.rb
module DebugHomepageHelper
end

app/views/debug_homepage/index.html.erb
<h1>Debug Homepage</h1>
<hr/>
<h3>Debug Scaffolds</h3>
<%= link_to 'Character Scaffold', characters_path %><br/>
<%= link_to 'Contacts Scaffold', contacts_path %><br/>
<%= link_to 'Character Contacts Scaffold', character_contacts_path %><br/>
<%= link_to 'Chummer Download', controller: 'chummer_download', action: 'index' %><br/>
<hr/>
<h3>Listing Debug</h3>
<%= link_to 'Skill Listings', controller: 'listing_debug', action: 'skills' %><br/>
<%= link_to 'Quality Listings', controller: 'listing_debug', action: 'qualities' %><br/>
<%= link_to 'Item Listings', controller: 'listing_debug', action: 'items' %><br/>