config/routes.rb
Rails.application.routes.draw do
  get 'available_skills_debug/index'
  resources :character_contacts
  resources :contacts
  get 'debug_homepage/index'
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/chummer_download", to:'chummer_download#index'
  post "/chummer_download/download", to: 'chummer_download#download'
  resources :characters
  get "/character/upload", to:"characters#upload_user_side"
  post "/character/upload", to:"characters#upload"
  get '/listings/skills', to:'listing_debug#skills'
  get '/listings/qualities', to:'listing_debug#qualities'
  get '/listings/items', to:'listing_debug#items'
  root to: 'debug_homepage#index'
end

app/models/contact.rb
class Contact < ApplicationRecord
    has_many :character_contact, dependent: :delete_all
    def to_chum5_nokogiri()
        Nokogiri::XML(to_chum5_xml()).children[0]
    end
    def to_chum5_xml()
        Nokogiri::XML::Builder.new do |xml|
            xml.contact{
                xml.name name
                xml.role archetype
                xml.location location
                xml.connection connection
                xml.loyalty 0
                xml.metatype metatype
                xml.sex sex
                xml.age age
                xml.contacttype contact_type
                xml.preferredpayment
                xml.type 'Contact'
                xml.file nil
                xml.relative nil
                xml.notes notes
                xml.groupname nil
                xml.colour -2830136
                xml.group group
                xml.family false
                xml.blackmail false
                xml.free false
                xml.groupenabled false
                # Need to generate a guid or a uuid
                xml.guid SecureRandom.uuid
                xml.mainmugshotindex -1
                xml.mugshots nil
            }
        end.to_xml
    end
    class << self
        def contacts_from_chum5_xml(nokogiri_document)
            nokogiri_document.xpath('.//contacts/contact').each do |contact|
                contact_from_chum5_xml(contact)
            end
        end
        def contact_from_chum5_xml(nokogiri_node)
            #Duplicating the node so we don't lose data.
            node=nokogiri_node.dup
            contact=Contact.new()
            # Grabbing Contact Name
            contact.name= node.xpath('.//name/text()').to_s
            # Grabbing Contact Location
            contact.location= node.xpath('.//location/text()').to_s
            # Grabbing Contact Archetype
            contact.archetype= node.xpath('.//role/text()').to_s
            # Grabbing other data . . . 
            contact.metatype=node.xpath('.//metatype/text()').to_s
            contact.sex=node.xpath('.//sex/text()').to_s
            contact.age=node.xpath('.//age/text()').to_s
            contact.prefered_payment=node.xpath('.//preferredpayment/text()').to_s
            contact.hobbies_vice=node.xpath('.//hobbiesvice/text()').to_s
            contact.personal_life=node.xpath('.//personallife/text()').to_s
            contact.group=node.xpath('.//group/text()').to_s.downcase[0]=='t'
            contact.connection=node.xpath('.//connection/text()').to_s.to_i
            contact.contact_type=node.xpath('.//contacttype/text()').to_s
            # Grabbing Notes!
            contact.notes=node.xpath('.//notes/text()').to_s
            # Purging Loyalty
             node.xpath('.//loyalty').remove
            # Saving Data
            contact.data= node.to_s
            # Last Step: Setting Visible, and player_custom to false and true respectively
            contact.visible=false;
            contact.player_custom=true;
            contact.save!
            # And Just to make our lives easier ... we are going to return the contact.
            contact
        end
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.character_contact.each{|cc| cc.destroy}
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :location, :archetype, :data, :visible, :player_custom)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :archetype %>
    <%= form.text_field :archetype %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data %>
  </div>

  <div class="field">
    <%= form.label :visible %>
    <%= form.check_box :visible %>
  </div>

  <div class="field">
    <%= form.label :player_custom %>
    <%= form.check_box :player_custom %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Connection</th>
      <th>Location</th>
      <th>Archetype</th>
      <th>Metatype</th>
      <th>Sex</th>
      <th>Age</th>
      <th>Prefered Payment</th>
      <th>Hobbies/Vice</th>
      <th>Personal Life</th>
      <th>Notes</th>
      <th>Group</th>
      <th>Visible</th>
      <th>Player custom</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.connection%></td>
        <td><%= contact.location %></td>
        <td><%= contact.archetype %></td>
        <td><%= contact.metatype %></td>
        <td><%= contact.sex %></td>
        <td><%= contact.age %></td>
        <td><%= contact.prefered_payment %></td>
        <td><%= contact.hobbies_vice %></td>
        <td><%= contact.personal_life %></td>
        <td><%= contact.notes %></td>
        <td><%= contact.group %></td>
        <td><%= contact.visible %></td>
        <td><%= contact.player_custom %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<table class='contact_border'> 
  <thead>
    <tr>
      <th colspan=2>Name</th>
      <th>Contact Type</th>
    </tr>
  </thead>
  <tbody>
    <td colspan=2 style='text-align:center'><%= @contact.name %></td>
    <td><%= @contact.contact_type %></td>
  </tbody>
  <thead>
    <tr>
      <th>Connection</th>
      <th>Location</th>
      <th>Archetype</th>
    </tr>
  </thead>
  <tbody>
    <td><%= @contact.connection %></td>
    <td><%= @contact.location %></td>
    <td><%= @contact.archetype %></td>
  </tbody>
  <thead>
    <tr>
      <th>Prefered Payment</th>
      <th>Hobbies/Vice</th>
      <th>Personal Life</th>
    </tr>
  </thead>
  <tbody>
    <td><%= @contact.prefered_payment %></td>
    <td><%= @contact.hobbies_vice %></td>
    <td><%= @contact.personal_life %></td>
  </tbody>
  <tbody>
    <td colspan=2><%= link_to 'Edit', edit_contact_path(@contact) %></td>
    <td><%= link_to 'Delete', @contact, method: :delete, data: { confirm: "Are you sure?\n The folowing Characters will be effected: \n#{}" } %></td>
  </tbody>
</table>
<p>
  <strong>Notes:</strong>
  <%= simple_format(@contact.notes) %>
</p>

<p>
  <strong>Data:</strong>
  <%= @contact.data %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @contact.visible %>
</p>

<p>
  <strong>Player custom:</strong>
  <%= @contact.player_custom %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>