config/routes.rb
Rails.application.routes.draw do
  get 'available_skills_debug/index'
  resources :character_contacts
  resources :contacts
  get 'debug_homepage/index'
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/chummer_download", to:'chummer_download#index'
  post "/chummer_download/download", to: 'chummer_download#download'
  resources :characters
  get "/character/upload", to:"characters#upload_user_side"
  post "/character/upload", to:"characters#upload"
  get '/listings/skills', to:'listing_debug#skills'
  get '/listings/qualities', to:'listing_debug#qualities'
  get '/listings/items', to:'listing_debug#items'
  root to: 'debug_homepage#index'
end

app/models/character.rb
class Character < ApplicationRecord
    has_many :character_contact, dependent: :delete_all
    has_many :character_attribute, dependent: :delete_all
    has_many :character_skill, dependent: :delete_all
    has_many :character_quality, dependent: :delete_all
    has_many :character_item, dependent: :delete_all
    require 'json'
    #
    # @!attribute name
    #   @return [String] Name of the character
    # @!attribute ailias
    #   @return [String] Alias the character goes by
    # @!attribute images
    #   @return [Array<String>] Array of base64 formated images
    # @!attribute c_attributes
    #   @return [Hash<String, CharacterAttribute>] Hash of attributes associated with the character, with the name as the key
    # @!attribute skills
    #   @return [Hash<String, CharacterSkill>] Hash of skills associated with the character, with the name as the key
    # @!attribute qualities
    #   @return [Array<Array<String, CharacterQuality>>] Hash of qualities associated with the character, with the name as the key
    # @!attribute data
    #   @return [String] Unprocessed portion of the XML String
    #
    serialize :images, Array

    #
    # Converts the Character to a .chum5 string, ready to download
    #
    # @return [String] Chum5 Formated String
    #
    def to_chum5()
        puts "Exporting Chummer File"
        # Parsing Whatever Data we have left
        doc=Nokogiri::XML(data)
        Nokogiri::XML::Builder.with(doc.at_xpath('.//character')) do |xml|
            # Inserting Mugshots
            xml.mugshots{
                images.each{|image|
                    xml.mugshot image
                }
            }
            # Inserting All Contacts
            xml.contacts character_contact.map{|cc| cc=cc.to_chum5_xml()}.join("\n")
        end
        doc.to_xml
    end
    class << self
        #
        # Imports a .chum5 file uploaded by the user
        #
        # @param [String] file The File Location
        #
        # @return [Character] The Processed Character
        #
        def import_chum5(file)
            # Debug Code
            puts "Importing: #{file.path}"
            # Opening The File
            f=File.open(file.path,'r')
            data=f.read
            f.close
            # Parsing out the data we need from the file
            boop=Nokogiri::XML(data){|config| config.noent}
            c_alias=boop.xpath('.//alias/text()')[0]
            c_name=boop.xpath('.//name/text()')[0]
            mugshots=boop.xpath('.//mugshot/text()').map(&:text)
            boop.xpath('.//mugshots').remove
            # Creating Our shiny new Entry
            character=Character.create! alias: c_alias, name: c_name,  data: nil, images: mugshots
            # Ok we should go ahead and grab the things we need the character constructed for...
            CharacterContact.CharacterContacts_from_chum5_xml(character,boop)
            CharacterAttribute.attributes_from_chum5_xml(character,boop)
            CharacterSkill.skills_from_chum5_xml(character, boop)
            CharacterQuality.qualities_from_chum5_xml(character, boop)
            CharacterItem.items_from_chum5_xml(character,boop)
            boop.xpath('.//contacts').remove
            character.data=boop.to_s
            character.save!

            # More Debug Code
            puts "Imported!"
            puts "Alias: #{c_alias}"
            puts "Name: #{name}"
            puts "Mugshots: #{mugshots.length}"
            puts "Skills: "
        end
        private
        #
        # Turns a Nokogiri node into a JSON string recursively
        #
        # @param [Nokogiri::XML::Node, Nokogiri::XML::Document] node Source node to convert
        #
        # @return [String] JSONified node
        #
        def nokogiri_to_json(node)
            # Well Time for Horror inducing recursive code
            
            # Initial Test case, Are we looking at a document? if so return the first available node, run thru the function.
            return nokogiri_to_json(node.children[0]) if node.class==Nokogiri::XML::Document
            # Checking if it's an empty node
            return nil if node.nil?||(node.class==Nokogiri::XML::Text&&node.to_s.squish=="")
            # Ok Checking for bottom out condition, if we either arrive at a text node, or a empty value
            return node.to_s.dump if node.class==Nokogiri::XML::Text
            # Well We didn't Hit our Bottom out, so let's go ahead and grab our attributes (if any)
            attribute_string=''
            node.attributes.each do |k,v|
                attribute_string+="#{k.dump}:#{v.dump},"
            end
        
            # Let's wrap up our Attributes in a nice little package
            attribute_string="\"attributes\":{#{attribute_string[0..-2]}},"
            # Ok let's get started on doing the recursive bit, the value array
            value_string=""
            # Each Child we are adding a bit of data to our value_string, containing the results of this function ran on a subnode
            # OK there has to be a better way to do this ...
            node.children.each do |subnode|
                json=nokogiri_to_json(subnode)
                value_string+="#{json}, " unless json.nil?
            end
            # Wrapping up our value string in a nice little package
            value_string="\"value\":[#{value_string.gsub(/, $/,'')}]"
            # And Writing Our Node, with a nice little bow on top
            "{\"#{node.name}\":{#{attribute_string}#{value_string}}}"
        end
        #
        # Converts a JSON string to a Nokogiri Node
        #
        # @param [String] json JSON string
        #
        # @return [Nokogiri::XML:Node] Returned Nokogiri Noded
        #
        def json_to_nokogiri(json)
            Nokogiri::XML(json_to_xml(json))
        end
        #
        # Converts a JSON string to an XML Document
        #
        # @param [String] json formated string  
        #
        # @return [String] XML formated String
        #
        def json_to_xml(json)
            json_hash_to_xml(JSON.parse(json))
        end
        #
        # Converts a JSON hash (One that would be created from Nokogiri to JSON) to an XML Document
        #
        # @param [Hash] hash JSON Hash
        #
        # @return [String] XML Formtated String
        #
        def json_hash_to_xml(hash)
            # And Even more horor inducing code
        
            # Checking for Bottom case: Is what we are looking at a string?
            return hash if hash.class==String
            # Ok, Since we didn't hit the Bottom case, Let's go ahead and start out by grabing our keys...
            return_string=''
            hash.each do |tag,value| #bit silly, but makes it easier to grab ALL THE TAGS!
        
                # Ok Grabbing our Attributes
                attribute_string=''
                # Each one of Our attributes ...
                value['attributes'].each do |attribute|
                    # Grab The Attribute's Key and value ...
                    attribute.each do |k,v|
                        # And Shove it in our string!
                        attribute_string+="#{key}=\"#{value}\" "
                    end
                end
        
                # Next up: Let's grab the Child Nodes
                child_node_string=''
                value['values'].each do |child_node|
                    child_node_string+="#{json_hash_to_xml(child_node)}"
                end
                return_string+="<#{tag} #{attribute_string[0..-2]}>#{child_node_string}</#{tag}>"
            end
            return_string
        end
    end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    if !params[:format].nil? && params[:format].downcase=='chum5'
      char = Character.find(params[:id])
      send_data char.to_chum5, filename: "#{char.alias}.chum5", type: 'text/plain'
    end
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.character_contact.each do |cc|
      contact=cc.contact
      cc.destroy
      if(contact.player_custom && contact.character_contact.length==0)
        contact.destroy
      end
    end
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /character/upload
  # Just handles Uploading files userside
  def upload_user_side
  end
  
  # Uploads a chummer File
  # POST /character/upload
  def upload
    puts params[:file].path
    Character.import_chum5(params[:file])
    redirect_to characters_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      #params.require(:character).permit(:name, :data)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Characters</h1>

<table>
  <thead>
    <tr>
      <th>Alias</th>
      <th>Name</th>
      <th>Mugshot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.alias %></td>
        <td><%= character.name %></td>
        <td><%= image_tag "data:image/jpeg;base64,#{character.images[0]}", style:"width:200px;"%></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Upload Chummer file', character_upload_path %>
<br>
<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>
<p>
  <strong>Alias:</strong>
  <%= @character.alias %>
</p>
<table>
  <thead>
    <tr>
      <th>Contact</th>
      <th>Connection</th>
      <th>Loyalty</th>
      <th>Archetype</th>
      <th>Location</th>
    </tr>
  </thead>
  <tbody>
  <% @character.character_contact.each do |character_contact| %>
    <tr>
      <td><%= link_to character_contact.contact.name, character_contact.contact %></td>
      <td><%= character_contact.contact.connection %></td>
      <td><%= character_contact.loyalty %></td>
      <td><%= character_contact.contact.archetype %></td>
      <td><%= character_contact.contact.location %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<table>
  <thead>
    <th>Attribute</th>
    <th>Total</th>
  </thead>
  <tbody>
    <% @character.character_attribute.each do |attrib| %>
      <tr>
        <td><%= attrib.name %></td>
        <td><%= attrib.total %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Skill Name</th>
      <th>Specialization</th>
      <th>Total Points</th>
    </tr>
  </thead>
  <tbody>
    <% @character.character_skill.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
        <td><%= skill.specialization %></td>
        <td><%= skill.total %>
      </tr>
    <% end %>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th>Quality Name</th>
      <th>Quality Extra</th>
    </tr>
  </thead>
  <tbody>
    <% @character.character_quality.each do |quality| %>
      <tr>
        <td><%= quality.name %></td>
        <td><%= quality.extra %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% @character.character_item.each do |item| %>
  <% unless item.has_parent? %>
    <%= render "character_items/item_render", item: item %>
  <% end %>
<% end %>
<p>
  <strong>Data:</strong>
  <%= @character.data %>
</p>
<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/characters/upload_user_side.html.erb
<%= form_tag character_upload_path, multipart: true, method: :post do%>
<%= file_field_tag :file %>
<%= submit_tag "Import chum5" %>
<% end %> 